name: DeployAction

on:
  push:
    branches:
      - master
  issues:
    types: [edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public

      # - name: "trigger build"
      #   uses: BanzaiMan/travis-ci-action@master
      #   env:
      #     TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
      #     SLUG: "anuraghazra/gatsby-github-issues-blog"
      #     SITE: "org"